# Generated by Django 5.1 on 2024-08-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='rating',
        ),
        migrations.AlterField(
            model_name='recipes',
            name='difficulty',
            field=models.IntegerField(),
        ),
    ]
